-- INSERT INTO User(Id, firstName, lastName, userType) VALUES("ltwubben", "Luuk", "Wubben", "Employee");
-- INSERT INTO User(Id, firstName, lastName, userType) VALUES("vmadhu", "Veena", "Madhu", "Employee");
-- INSERT INTO User(Id, firstName, lastName, userType) VALUES("keshavnair", "Keshav", "Nair", "Employee");
-- INSERT INTO User(Id, firstName, lastName, userType) VALUES("npietnoczko", "Natalia", "Pietnoczko", "Employee");
-- INSERT INTO User(Id, firstName, lastName, userType) VALUES("bserbanescu", "Bianca", "Serbanescu", "Employee");
-- INSERT INTO User(Id, firstName, lastName, userType) VALUES("dsavastre", "Dan", "Savastre", "Employee");