INSERT INTO room (ID, NAME, CAPACITY, EQUIPMENT, AVAILABLE, BUILDING_NUMBER) VALUES (1, 'Europe', 12, 'whiteboard', 'available', 1);
INSERT INTO room (ID, NAME, CAPACITY, EQUIPMENT, AVAILABLE, BUILDING_NUMBER) VALUES (2, 'Steve Jobs', 15, 'beamer', 'maintenance', 1);
INSERT INTO room (ID, NAME, CAPACITY, EQUIPMENT, AVAILABLE, BUILDING_NUMBER) VALUES (3, 'Marie Curie', 8, 'extra chairs', 'available', 2);
INSERT INTO building (ID, OPENING_TIME, CLOSING_TIME, NAME) VALUES (1, '08:00', '18:00', 'Library');
INSERT INTO building (ID, OPENING_TIME, CLOSING_TIME, NAME) VALUES (2, '00:00', '00:00', 'EEMCS');
